#!/usr/bin/env bash

webhook_url=$FIREDRILL_WEBHOOK_URL

# help function
function help(){
  echo "$0 [role] [message]"
  echo "? and ! must be escaped, best to put your message in quotes so that stuff like apostrophes work properly"
}

if [ $# -lt 1 ]; then
  help
  exit 1
fi

# Make $role uppercase and encode spaces
role=$(echo $1 | awk '{print toupper($0)}')

# Tidy up some of the stuff in @message
message=${@:2}
message=$(echo $message | sed 's/\\//g')

case $role in
  TECHOPS|SD)
    image="https://cdn1.iconfinder.com/data/icons/user-pictures/100/supportmale-512.png";
    username="FIREDRILL (TECHOPS)";;
  SLM)
    image="https://cdn1.iconfinder.com/data/icons/user-pictures/100/female1-512.png";
    username="FIREDRILL (SLM)";;
  DIRECTOR)
    image="https://cdn1.iconfinder.com/data/icons/user-pictures/101/malecostume-512.png";
    username="FIREDRILL (DIRECTOR)";;
  HELP)
    help;exit 1;;
  START)
    username="FIREDRILL";
    message="*FIREDRILL START: $(date +%H\:%M)* ";
    image="https://cdn4.iconfinder.com/data/icons/ballicons-2-free/100/match-512.png";;
  STOP)
    username="FIREDRILL";
    message="*FIREDRILL STOP: $(date +%H\:%M)* ";
    image="https://cdn4.iconfinder.com/data/icons/ballicons-2-free/100/match-512.png";;
  *)
    image="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png";
    username="FIREDRILL ($role)";;
esac

# Build request
request_body=$(cat <<EOF
{
  "text": "$message",
  "username": "$username",
  "icon_url": "$image"
}
EOF
)

# Fire it off!
curl -X POST -d "$request_body" $webhook_url && echo
